apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  #프로비저닝된 노드의 파라미터를 제한하는 요구 사항
  #연산자 { In, NotIn }은 값을 포함하거나 제외할 수 있도록 하기 위해 지원됨
  requirements:
    - key: "kubernetes.io/arch"
      operator: In
      values: ["arm64"]
    - key: "karpenter.sh/capacity-type" # If not included, the webhook for the AWS cloud provider will default to on-demand
      operator: In
      values: ["spot", "on-demand"]
  provider:
    instanceProfile: eks-22c40738-3e4f-a670-408f-7101dd0d467b
    subnetSelector:
      kubernetes.io/cluster/$CLUSTER_NAME: "ddps-jg"
    securityGroupSelector:
      kubernetes.io/cluster/$CLUSTER_NAME: "ddps-jg"
  ttlSecondsAfterEmpty: 30
