apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  #프로비저닝된 노드의 파라미터를 제한하는 요구 사항
  #연산자 { In, NotIn }은 값을 포함하거나 제외할 수 있도록 하기 위해 지원됨
  requirements:
    - key: "kubernetes.io/arch"
      operator: In
      values: ["arm64"]
    - key: "karpenter.sh/capacity-type" # If not included, the webhook for the AWS cloud provider will default to on-demand
      operator: In
      values: ["on-demand"]
  provider:
    subnetSelector:
      karpenter.sh/discovery: "jg"
    securityGroupSelector:
      karpenter.sh/discovery: "jg"
    tags:
      karpenter.sh/discovery: "jg"
  ttlSecondsAfterEmpty: 30
# ---
# apiVersion: karpenter.k8s.aws/v1alpha1
# kind: AWSNodeTemplate
# metadata:
#   name: default
# spec:
#   subnetSelector:
#     aws-ids: "subnet-08b33f66f3340baaf, subnet-0467d7cc73fd7b976"
#   securityGroupSelector:
#     aws-ids: "sg-0074e6eb836cfeadd"
