apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  #프로비저닝된 노드의 파라미터를 제한하는 요구 사항
  #연산자 { In, NotIn }은 값을 포함하거나 제외할 수 있도록 하기 위해 지원됨
  requirements:
    - key: "karpenter.sh/capacity-type" # If not included, the webhook for the AWS cloud provider will default to on-demand
      operator: In
      values: ["on-demand"]
  provider:
    subnetSelector:
      karpenter.sh/discovery: <cluster_name>
    securityGroupSelector:
      karpenter.sh/discovery: <cluster_name>
    tags:
      karpenter.sh/discovery: <cluster_name>
  ttlSecondsAfterEmpty: 30
