---
apiVersion: v1
kind: Namespace
metadata:
  name: bentoml-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: bentoml-namespace
  labels:
    app: bentoml-service
  name: bentoml-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bentoml-service
  strategy: {}
  template:
    metadata:
      labels:
        app: bentoml-service
    spec:
      containers:
      - image: kmubigdata/mlserving:latest
        name: pytorch-resnet50
        resources: {}
        ports:
        - containerPort: 3000
---
### BentoService
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bentoml-service
  name: bentoml-service
  namespace: bentoml-namespace
spec:
  ports:
    - name: predict
      port: 3000
      targetPort: 3000
  selector:
    app: bentoml-service
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: bentoml-namespace
  name: bentoml-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /predict
spec:
  ingressClassName: nginx
  rules:
    - host: <YOUR URL>
      http:
        paths:
        - path: /bento
          pathType: Prefix
          backend:
            service:
              name: bentoml-service
              port:
                number: 3000
---
### BentoService ServiceMonitor
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bentoml-service
  namespace: bentoml-namespace
spec:
  selector:
    matchLabels:
      app: bentoml-service
  endpoints:
  - port: predict