apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: bentoserve
  name: bentoserve
spec:
  replicas: 5
  selector:
    matchLabels:
      app: bentoserve
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bentoserve
    spec:
      containers:
      - image: kmubigdata/mlserving:latest
        name: pytorch-resnet50
        resources: {}
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: bentoserve-service
spec:
  type: ClusterIP
  selector:
    app: bentoserve
  ports:
    - name: http
      port: 80
      targetPort: 3000