variable "cluster_prefix" {}
variable "cluster_sg_id" {}
variable "master_node_number" {}
variable "instance_type" {}
variable "vpc" {}
variable "private_subnet_ids" {}
variable "ubuntu_ami" {}
variable "ec2_instance_profile" {}
variable "key_name" {}
variable "private_subnet" {}