- name: Get join command from first master node
  hosts: first-kube-master
  gather_facts: false
  tasks:
    - name: Get join command
      ansible.builtin.command: kubeadm token create --print-join-command
      register: join_command_raw
      changed_when: false
    - name: Set join command
      ansible.builtin.set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- name: Join worker nodes to k8s cluster
  hosts: kube-node
  gather_facts: false
  tasks:
    - name: Join cluster
      become: true
      ansible.builtin.command: "{{ hostvars[groups['first-kube-master'].0].join_command }}"
      changed_when: false
